## Pandas
- Data analysis and manipulation tool

### Import

In [3]:
import pandas as pd

### Series in Pandas(1D labeled array)

## Series Properties:
- Homogenous
- Vectorized Operations
- Handle Missing values with NaN
- Mutable values,immutable size

In [4]:
s=pd.Series([1,2,3,4,5])
s

#index based access
print(s)
print(s[0])

0    1
1    2
2    3
3    4
4    5
dtype: int64
1

In [5]:
#Label based access
#Homogenous
s=pd.Series([23,34,45,56,"abe"],index=["Adam","Eve","Bob","Charlie",25])
print(s)
print(s["Adam"])
print(s["Bob"])
print(s["Eve"])
print(s["Charlie"])

Adam        23
Eve         34
Bob         45
Charlie     56
25         abe
dtype: object
23
45
34
56

In [6]:
#Vectorized Operations
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([10,20,30,40,50])
print(s1+s2)

0    11
1    22
2    33
3    44
4    55
dtype: int64

### DataFrame

In [7]:
info={
    "Name":["Shyamal","Shivam","Soubam","Sandhya"],
    "Age":[24,26,24,24],
    "GPA":[7.1,7.5,8.9,8.7]
}
df=pd.DataFrame(info)
print(df,type(df))
print(df.index)
print(df.columns)

      Name  Age  GPA
0  Shyamal   24  7.1
1   Shivam   26  7.5
2   Soubam   24  8.9
3  Sandhya   24  8.7 <class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'Age', 'GPA'], dtype='object')

In [8]:
df

      Name  Age  GPA
0  Shyamal   24  7.1
1   Shivam   26  7.5
2   Soubam   24  8.9
3  Sandhya   24  8.7

### Working of Numpy with Dataframe

In [9]:
import numpy as np
np_array=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(np_array,columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

### Usage of Pandas with csv and json files
- For any organisation or for any project ,the data that has been shared with us in majority cases it will going to be in the .csv format/json files/sql format.
- why .csv?
 - this format works well with python and even with R lang which is used for Data science,also works well with sql.

In [10]:
import json
content=[
      {
        "ID": 1,
        "Name": "Alice",
        "Age": 25,
        "Department": "HR",
        "Salary": 55000
      },
      {
        "ID": 2,
        "Name": "Bob",
        "Age": 32,
        "Department": "IT",
        "Salary": 72000
      },
      {
        "ID": 3,
        "Name": "Charlie",
        "Age": 28,
        "Department": "Finance",
        "Salary": 48000
      },
      {
        "ID": 4,
        "Name": "David",
        "Age": 45,
        "Department": "Marketing",
        "Salary": 91000
      },
      {
        "ID": 5,
        "Name": "Eva",
        "Age": 38,
        "Department": "IT",
        "Salary": 65000
      },
      {
        "ID": 6,
        "Name": "Frank",
        "Age": 29,
        "Department": "Finance",
        "Salary": 50000
      },
      {
        "ID": 7,
        "Name": "Grace",
        "Age": 41,
        "Department": "HR",
        "Salary": 82000
      },
      {
        "ID": 8,
        "Name": "Hannah",
        "Age": 26,
        "Department": "Marketing",
        "Salary": 47000
      },
      {
        "ID": 9,
        "Name": "Ian",
        "Age": 35,
        "Department": "IT",
        "Salary": 75000
      },
      {
        "ID": 10,
        "Name": "Julia",
        "Age": 30,
        "Department": "Finance",
        "Salary": 60000
      }]
with open("employee_data.json","w") as f:
    json.dump(content,f)
    """
        with open("employee_data.json","r") as f:
        data=json.load(f)
        print(data)
    """
#Reading csv data
df=pd.read_csv("employee_data.csv")
print(df,type(df))

print("\n")

#Reading json data
df=pd.read_json("employee_data.json")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>


   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

### To read excel and sql files:
- pd.read_excel() and pd.read_sql()

### DataFrame Methods
- These methods helps in Initial EDA i.e., Data Exploration Analysis

In [11]:
#methods
print(df.head())#starting 5 rows
print("\n")
print(df.tail()) #trailing 5 rows
print("\n")
print(df.tail(2)) #trailing n=2 rows
print("\n")
print(df.sample(3)) # n=3 random value
print("\n")
print(df.info()) # summary of data
print("\n")
print(df.shape) # returns tuple of row and column value
print("\n")
df.describe() #important statistics of the numerical columns
print("\n")
print(df.columns)
print("\n")
print(df.nunique())

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000


   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000


   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000


   ID     Name  Age Department  Salary
2   3  Charlie   28    Finance   48000
7   8   Hannah   26  Marketing   47000
9  10    Julia   30    Finance   60000


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes
None


(10, 5)




Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')


ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [12]:
df

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

### Using Kaggle dataset

In [13]:
#AQI data set
df=pd.read_csv("globalAirQuality.csv")
#print(df.head())

#df.tail()
#df.columns
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

### Selecting Data  from Pandas 
- Select Columns
- Select Rows(Label and Index based)-loc & iloc
- Select Rows and Columns
- Select single scalar value-at &iat

- Difference between index and label will be known when we are gonna use slice

In [14]:
#selecting data

#columns
df[["city","aqi","country"]]

#rows
#Label-Based
df.loc[0]
df.loc[0:2] #start idx:end idx(inclusive)
 
#Index-Based
df.iloc[2]
df.iloc[0:2] #start idx:end idx(exclusive)

#label based access for selecting rows-columns
#cell-rows & columns
df.loc[0,"aqi"]
df.loc[0,["city","aqi"]]
df.loc[0:2,["city","aqi"]]

#index based access for selecting rows-columns
#requires traditional index values not a string
df.iloc[0:2,2]

#assignment
df.loc[0,["country","city","latitude","longitude"]]
df.iloc[0:1,1:5]

#selecting single scalar value- at & iat
df.at[0,"city"]
df.iat[0,2]

#whenever we knew that there is gonna be a change in the original data but u want to avoid the change in the 
#original data just use .copy().E.g.,
cities=df["city"].copy()
cities[0]="Mumbai"
cities

0          Mumbai
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [15]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

### Filtering of Data

In [16]:
df[df["aqi"]>100]
df[(df["aqi"]>100) & (df["temperature"]>30)]
df[(df["aqi"]>100) & (df["temperature"]<30)]
df[df["aqi"]>100][["country","city","aqi"]]
df[(df["aqi"]>100) & (df["temperature"]>30)][["country","city","aqi","temperature"]]
#The original label of the data is preserved in the filtered data
#After filtering the data ,automatically pandas cannot change the label
#why??
#maybe it can happen that the label we assigned may have some actual meaning.
#Therefore pandas, mistakenly cannot change the label in the original data.Therefore,the label information 
#by default,its preserved.

#here,we will know the difference between label and Index
aqi_data=df[(df["aqi"]>100) & (df["temperature"]>30)][["country","city","aqi","temperature"]]
aqi_data
aqi_data.iloc[0]#which is a index-based
#aqi_data.loc[0]# will show u an error because label inside the loc does not match with the any given label
aqi_data.loc[6]# will not show u an error because label inside the loc match with the any given label.

country              US
city           New York
aqi                 155
temperature      36.729
Name: 6, dtype: object

In [17]:
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

## Filtering Data using Query

### query() rules
- Expression as a string
- Column based reference
- Backticks for col_name with space or special chars
- Operators(&,|,~,>=,<=,==,<,>,etc)
- @ to reference python vars
- Chained comparisons

# Data Cleaning
- handling Null vals or missing values.
- Deduplication.
- Understanding different types of data,so that if we have variety of data we can able to standardize them.

## Handle missing Values

- isnull()/isna()[alias of isnull()]
- isnull().sum()
    - how it is helpful??
- dropna()
- fillna(value)
- ffill()
    - forward fill:It fills missing values (NaN) using the previous valid value in the column or row.
- bfill()
    - backward fill:It fills missing values (NaN) using the next valid value in the column or row.

In [18]:
#Cleaning Data-missing values

df=pd.read_csv("raw_data.csv")

#detect empty val
df.isnull()
#or
df.isna()

#counting the number of missing value per column
df.isnull().sum()

#drop all the null value from our data
df.dropna()#row drop
df.dropna(axis=1)#col drop

#fill the missing value with particular value
df.fillna(0)

#fill the missing value of the column-age and replace them with mean value of the age
age_mean=df["age"].mean()
df["age"].fillna(age_mean)# even the null data is retained,the original data remain unchanged

#To make the change in the original data,copy the original data and store it in the other variable
cleaned_data=df.copy()
age_mean=cleaned_data["age"].mean()
cleaned_data["age"]= cleaned_data["age"].fillna(age_mean)
cleaned_data

#Forward Fill and Backward Fill
df.ffill()
df.bfill()
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [19]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## Handle Duplicate Values

- deduplicated()
- drop_duplicates()

In [20]:
df.duplicated()
df[["country","gender"]].duplicated()
df2=df.copy()
df2.drop_duplicates()
#To make change in the original data
df2.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [21]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## Handle Data type & date-time
- dtypes()
    - print the types of data 
- astype(newType)
    - change the type of data
- to_datetime()
    - change the normal data to pandas date/time data type

In [22]:
# Data Types
df.dtypes

#change the data to new_type
df2=df.copy()
df2=df2.fillna(0)
df2=df2["age"].astype("int64").copy()
df2.dtypes
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [23]:
df2.dtypes

dtype('int64')

In [24]:
aqi_data=pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"]=pd.to_datetime(aqi_data["timestamp"])

In [25]:
aqi_data["timestamp"].dtypes

dtype('<M8[ns]')

## Handle Strings
- .str.lower(),str.upper() & .str.capitalize()
- .str.strip()
- .str.split(" ")
- .str.contains(val,ase=False)

In [26]:
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()
df["name"].str.split(" ")
df["country"].str.contains("usa",case=False) #ignore the upper/lower case

0      True
1      True
2     False
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10     True
Name: country, dtype: object

## Feature Engineering(Transforming Data)-transforming data to create some neew columns or features that improves the performance of our models.
- apply()
    - used to apply a function to each element, row, or column of a DataFrame or Series.
    - it is a HOF(High Order Function).It means it accepts another function as an argument.
- map()
    - used to transform each value in a Series using a function, dictionary, or another mapping.
- assign()
    - used to create new columns or assign values to columns in a DataFrame. It returns a new DataFrame rather than           modifying the original DataFrame by default.
- replace(old,new)
    - used to replace specific values in a Series or DataFrame with new values.
- rename(columns={old:new})
    - used to change the names of rows (index labels) or columns in a DataFrame.
- sort_values()
    - Sorts rows based on the values in a particular column.
- sort_index()
    - Sorts rows according to their index labels.
- reset_index()
    - Resets the row index to the default sequence 0, 1, 2, ....
- rank()
    - Assigns ranks to values in a column.
    - methods in rank()
        - "average"	Average rank for tied values (default)
        - "min"	Assign the lowest rank to tied values
        - "max"	Assign the highest rank to tied values
        - "first"	Rank ties in their order of appearance
        - "dense"	Like "min", but without gaps in ranks
- Reorder columns
    - you can reorder columns by passing the desired column order inside double square brackets [[ ]].

In [27]:
#feature Engineering

#creating a new column where we can calculate tax on an existing data
#apply()
df2=df.copy()
df2["tax"]=df2["income"].apply(lambda x:"20%" if x >= 60000 else "10%")
df2

#map()
gender_map={"Male":"M","Female":"F","Unknown":"U"}
df2["gender"]=df2["gender"].map(gender_map)
df2

#assign()
df2=df2.assign(new_income=df2["income"]*1.1)

#replace()
df2["country"]=df2["country"].replace("USA","United States")
df2

#rename()
df2.columns=["Id","Name","Age","Coutry","Gender","Income","Tax","New_income"]
df2=df2.rename(columns={"Income":"Salary","New_income":"New_salary"})
df2.rename(index={1:"First"})
df2
#sort_values()
df2.sort_values("Salary")
df2.sort_values("Salary",ascending=False)
sorted_data=df2.sort_values(["Salary","Age"])
sorted_data

#sort_index()
sorted_data.sort_index()

#reset_index()
#it preserved the original index values,therefore a new column is created named as index
sorted_data.reset_index()
#if u dont want to preserved the original data
sorted_data.reset_index(drop=True)


#rank()
sorted_data["Ranking"]=sorted_data["Salary"].rank(ascending=False,method="dense")
sorted_data

#reorder_column
sorted_data[["Id","Name","Age","Coutry","Gender","Tax","Salary","New_salary","Ranking"]]
sorted_data=sorted_data.rename(columns={"Coutry":"Country"})
sorted_data

,Id,Name,Age,Country,Gender,Salary,Tax,New_salary,Ranking
9,9,Carlos Ruiz,NaN,Mexico,M,45000.0,10%,49500.0,8.0
3,3,Alex,NaN,United States,U,47000.0,10%,51700.0,7.0
5,5,Li Wei,27.0,China,M,51000.0,10%,56100.0,6.0
0,1,John Doe,29.0,United States,M,55000.0,10%,60500.0,5.0
1,1,John Doe,29.0,United States,M,55000.0,10%,60500.0,5.0
10,10,Emily Davis,31.0,United States,NaN,58000.0,10%,63800.0,4.0
8,8,Rachel Lee,29.0,United States,F,62000.0,20%,68200.0,3.0
2,2,Jane Smith,NaN,Canada,F,62000.0,20%,68200.0,3.0
7,7,Ahmed Khan,38.0,NaN,M,68000.0,20%,74800.0,2.0
6,6,NaN,45.0,India,F,73000.0,20%,80300.0,1.0
4,4,Maria Garcia,34.0,Spain,F,NaN,10%,NaN,NaN

In [28]:
df2

    Id          Name   Age         Coutry Gender   Salary  Tax  New_salary
0    1      John Doe  29.0  United States      M  55000.0  10%     60500.0
1    1      John Doe  29.0  United States      M  55000.0  10%     60500.0
2    2    Jane Smith   NaN         Canada      F  62000.0  20%     68200.0
3    3          Alex   NaN  United States      U  47000.0  10%     51700.0
4    4  Maria Garcia  34.0          Spain      F      NaN  10%         NaN
5    5        Li Wei  27.0          China      M  51000.0  10%     56100.0
6    6           NaN  45.0          India      F  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0            NaN      M  68000.0  20%     74800.0
8    8    Rachel Lee  29.0  United States      F  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN         Mexico      M  45000.0  10%     49500.0
10  10   Emily Davis  31.0  United States    NaN  58000.0  10%     63800.0

In [29]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

## Tasks-Shifts id column to the end

In [30]:
df3=df.copy()
new_column_order=[col for col in df3.columns if col !="id"] +["id"]
df3[new_column_order]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

# Writing to csv

In [40]:
import pandas as pd
df2=df.copy()
df2=df2.drop_duplicates()
df2=df2.fillna(0)
df2=df2.sort_values("income")
df2=df2.reset_index(drop=True)
df2["gender"]=df2["gender"].map({
    "Male":"M",
    "Female":"F",
    "Unknown":"U"
})
df2.columns=["Id","Name","Age","Country","Gender","Income"]
df2=df2.rename(columns={"Income":"Salary"})
df2=df2.fillna(0)
df2["Gender"]=df2["Gender"].replace(0,"U")
df2.to_csv("sorted_data.csv")
df2

   Id          Name   Age Country Gender   Salary
0   4  Maria Garcia  34.0   Spain      F      0.0
1   9   Carlos Ruiz   0.0  Mexico      M  45000.0
2   3          Alex   0.0     USA      U  47000.0
3   5        Li Wei  27.0   China      M  51000.0
4   1      John Doe  29.0     USA      M  55000.0
5  10   Emily Davis  31.0     USA      U  58000.0
6   2    Jane Smith   0.0  Canada      F  62000.0
7   8    Rachel Lee  29.0     USA      F  62000.0
8   7    Ahmed Khan  38.0       0      M  68000.0
9   6             0  45.0   India      F  73000.0

# Grouping and Aggregation of Data
- groupby()
    - used to group rows with the same value and perform operations such as sum(), mean(), count(), and max() on each group.
- mean/sum/max/min/count etc.
- agg()
    - used to apply multiple summary functions to a DataFrame or to groups created using groupby().

In [48]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [65]:
df.groupby("country")["income"].mean()
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()
df.groupby("country")["income"].count()

df.groupby("gender")["income"].mean()
df.groupby("gender")["income"].min()
df.groupby("gender")["income"].max()

#agg() or aggregate()
df.groupby("country")["income"].agg(["mean","min","max"])
df.groupby("country")["income"].aggregate(["mean","min","max"])
#renaming the column
df.groupby("country")["income"].aggregate(avg_salary="mean",minimum="min",maximum="max")

#Applying different aggregate function to different columns
df.groupby("country").agg({
    "income":"max",
    "age":"mean"
})
df.groupby("country").agg(
    max_salary=("income","max"),
    avg_age=("age","mean")
)

         max_salary  avg_age
country
Canada      62000.0      NaN
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      NaN
Spain           NaN     34.0
USA         62000.0     29.5

# Important Operation in Pandas
- melt
    - wide data to long format data
    - melt(id_vars,value_vars,var_name,value_name)
- Pivot
    - long data to wide format data
    - pivot(index,columns,values)

In [90]:
#melt & pivot
import pandas as pd
sales={
    "country":["USA","India","Russia","China"],
    "year":[2021,2020,2023,2024],
    "sales":[100,120,90,130],
    "profit":[20,40,10,43],
    "C_code":[12,91,23,45]
}
df=pd.DataFrame(sales)
melted_df=df.melt(
    id_vars=["country","year"],
    value_vars=["sales","profit","C_code"],
    var_name="matrics",
    value_name="values"
)
original=melted_df.pivot(
    index=["country","year"],
    columns="matrics",
    values="values"
)

In [91]:
original

matrics       C_code  profit  sales
country year
China   2024      45      43    130
India   2020      91      40    120
Russia  2023      23      10     90
USA     2021      12      20    100

In [89]:
df

  country  year  sales  profit  C_code
0     USA  2021    100      20      12
1   India  2020    120      40      91
2  Russia  2023     90      10      23
3   China  2024    130      43      45

In [88]:
melted_df

   country  year matrics  values
0      USA  2021   sales     100
1    India  2020   sales     120
2   Russia  2023   sales      90
3    China  2024   sales     130
4      USA  2021  profit      20
5    India  2020  profit      40
6   Russia  2023  profit      10
7    China  2024  profit      43
8      USA  2021  C_code      12
9    India  2020  C_code      91
10  Russia  2023  C_code      23
11   China  2024  C_code      45

# Merging and Joining Data
- Inner Join
- Left Join
- Right Join
- Outer Join

In [92]:
#Merging and Joining data
df_customers=pd.DataFrame(
    {
        "customer_id":[1,2,3,4],
        "name":["Shyamal","Shivam","Soubam","Akash"]
    }
)
df_order=pd.DataFrame({
    "order_id":[101,102,103,104],
    "customer_id":[2,1,4,5],
    "amount":[250,120,340,530]
})

In [95]:
df_customers

   customer_id     name
0            1  Shyamal
1            2   Shivam
2            3   Soubam
3            4    Akash

In [96]:
df_order

   order_id  customer_id  amount
0       101            2     250
1       102            1     120
2       103            4     340
3       104            5     530

In [100]:
#inner join
pd.merge(df_customers,df_order,on="customer_id")
#left join
pd.merge(df_customers,df_order,on="customer_id",how="left")
#right join
pd.merge(df_customers,df_order,on="customer_id",how="right")
#outer join
pd.merge(df_customers,df_order,on="customer_id",how="outer")

   customer_id     name  order_id  amount
0            1  Shyamal     102.0   120.0
1            2   Shivam     101.0   250.0
2            3   Soubam       NaN     NaN
3            4    Akash     103.0   340.0
4            5      NaN     104.0   530.0

## Data Concatenation 
- Stacking DataFrames on top of each other(rows) or side by side (columns)
- how it is helpful?
    - Suppose we are fetching data through API calls or retrieving data from a database. Sometimes, due to rate limits or other restrictions, we cannot fetch the entire dataset at once. In such cases, we fetch the data in smaller batches and store each batch in a separate DataFrame.
Eventually, we want to combine all these DataFrames into a single DataFrame. We use data concatenation in Pandas to combine these separate DataFrames into one dataset.

In [102]:
#Concatenation
df1=pd.DataFrame({
    "id":[1,2,3],
    "name":["Shyamal","Shivam","Soubam"],
})
df2=pd.DataFrame({
    "id":[4,5,6],
    "name":["Akash","Arup","Bikash"],
})

In [103]:
df1

   id     name
0   1  Shyamal
1   2   Shivam
2   3   Soubam

In [104]:
df2

   id    name
0   4   Akash
1   5    Arup
2   6  Bikash

In [108]:
pd.concat([df1,df2])#row
pd.concat([df1,df2],ignore_index=True)#overwriting the original index

   id     name
0   1  Shyamal
1   2   Shivam
2   3   Soubam
3   4    Akash
4   5     Arup
5   6   Bikash

In [109]:
pd.concat([df1,df2],axis=1) #col

   id     name  id    name
0   1  Shyamal   4   Akash
1   2   Shivam   5    Arup
2   3   Soubam   6  Bikash